#
#  toyboxes.mk - include file auto-generated by toybox.py (https://toyboxpy.io).
#

_RELATIVE_FILE_PATH := $(lastword $(MAKEFILE_LIST))
_RELATIVE_DIR := $(subst /$(notdir $(_RELATIVE_FILE_PATH)),,$(_RELATIVE_FILE_PATH))

uniq = $(if $1,$(firstword $1) $(call uniq,$(filter-out $(firstword $1),$1)))
UINCDIR := $(call uniq, $(UINCDIR) $(_RELATIVE_DIR))

PDBASE_MAKEFILE := $(_RELATIVE_DIR)/github.com/DidierMalenfant/pdbase/pdbase.mk
MODPLAYER_MAKEFILE := $(_RELATIVE_DIR)/github.com/DidierMalenfant/modplayer/modplayer.mk

include $(PDBASE_MAKEFILE)
include $(MODPLAYER_MAKEFILE)
