//
//  toyboxes.h - include file auto-generated by toybox.py (https://toyboxpy.io).
//

#include "github.com/DidierMalenfant/pdbase/pdbase/pdbase.h"
#include "github.com/DidierMalenfant/modplayer/modplayer/modplayer.h"

#define REGISTER_TOYBOXES(pd)   register_pdbase(pd); \
                                register_modplayer(pd);
